# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudryavka', '0004_auto_20161026_1025'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to='created',
        ),
    ]
