# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudryavka', '0005_auto_20161026_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
